---
author: "takeR"
categories: ["suicide","symposium"]
date: 2017-02-02T22:32:38+09:00
description: ""
featured: ""
featuredalt: ""
featuredpath: ""
linktitle: ""
title: 2/26 (日)自殺リスクに関する研究会＠統計数理研究所
---


## 研究会の開催案内です。

--------
[第7回 自殺リスクに関する研究会](http://www.ism.ac.jp/risk/suicide_ws7.html)


> ### 概要

統計数理研究所にて開催されてきた自殺リスクに関する研究会は、本年度で最終回となります。これまで、多くの方にご支援いただきながら、自殺の問題に関するエビデンスを集積・展開するための方法論を議論してきました。最終回はこれまでの取り組みを振り返りながら、今後の展開を議論する会にできたらと考えております。皆様のご参加をお待ちしております。
 
> ### 日時

2017年2月26日(日) 10:30～14:00

> ### 場所  

統計数理研究所 セミナー室2（3階 D304室)  
（〒190-8562　東京都立川市緑町10-3）  

> ### 主催  

統計数理研究所 リスク解析戦略研究センター

> ### 後援  

厚生労働科学研究
　「学際的・国際的アプローチによる自殺総合対策の新たな政策展開に関する研究」
　（研究代表者：本橋豊（京都府立医科大学大学院医学研究科））




> ### プログラム

【セッション１　10:35-11:35  
　　「精神保健の疫学研究に携わって：精神科の受療データ解析を中心に」  
　　    立森 久照 (国立精神・神経医療研究センター 精神保健研究所)  
　　  
　　「自殺死亡の地域統計を用いた空間集積性の検出と視覚化」  
　　    久保田 貴文（多摩大学経営情報学部）  
　　  
　　「空間データ解析と可視化：精神保健福祉施策に向けた有効活用」  
　　    高橋 邦彦 （名古屋大学大学院医学系研究科 臨床医薬学講座生物統計学分野)  
  
昼休憩　 11:35-12:30  
  
【セッション２　12:30-13:50】  
　　「過量服薬の再発予防に向けた臨床疫学研究」  
　　    奥村 泰之 (一般財団法人医療経済研究・社会保険福祉協会 医療経済研究機構 研究部)  
　　  
　　「藤田先生の先行研究に学んだ精神保健統計の基礎」  
　　    河野 稔明 (国立精神・神経医療研究センター病院 司法精神科臨床研究センター)  
　　  
　　「30年間の市区町村自殺統計から見えてきた、地域間格差の実態と対策の課題」  
　　    岡 檀 (和歌山県立医科大学 地域イノベーション戦略支援プログラム)  
　　  
　　「市区町村の自殺対策と精神保健に係る資源配置との関連」   
　　    中西 三春 (東京都医学総合研究所 精神保健看護研究室)  
　
